// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// acsi_first //
// --------- //

#define acsi_first_wrap_target 0
#define acsi_first_wrap 5
#define acsi_first_pio_version 0

static const uint16_t acsi_first_program_instructions[] = {
            //     .wrap_target
    0x200b, //  0: wait   0 gpio, 11
    0x00c0, //  1: jmp    pin, 0
    0xa442, //  2: nop                           [4]
    0x4508, //  3: in     pins, 8                [5]
    0x208b, //  4: wait   1 gpio, 11
    0x8020, //  5: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program acsi_first_program = {
    .instructions = acsi_first_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = acsi_first_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config acsi_first_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + acsi_first_wrap_target, offset + acsi_first_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
#include "defs.h"
static PIO acsiFirstPio;
static uint acsiFirstSm;
void configAcsiFirst(void)
{
    // INT is controlled by gpio, always driving H
    gpio_set_function(PIN_INT, GPIO_FUNC_SIO);
    gpio_put(PIN_INT, 1);
    // DRQ is controlled by gpio, always driving H
    gpio_set_function(PIN_DRQ, GPIO_FUNC_SIO);
    gpio_put(PIN_DRQ, 1);
}
static inline void acsi_first_program_init(PIO pio, uint sm, uint offset)
{
    acsiFirstPio = pio;
    acsiFirstSm = sm;
    #define PIO_FIRST_COUNT 10
    int pio_pins[PIO_FIRST_COUNT] = {PIN_D0, PIN_D1, PIN_D2, PIN_D3, PIN_D4, PIN_D5, PIN_D6, PIN_D7, PIN_CS, PIN_A1};
    int pio_dirs[PIO_FIRST_COUNT] = {     0,      0,      0,      0,      0,      0,      0,      0,      0,      0};
    for (int i = 0; i < PIO_FIRST_COUNT; i++) {
        pio_gpio_init(pio, pio_pins[i]);
        pio_sm_set_consecutive_pindirs(pio, sm, pio_pins[i], 1, pio_dirs[i]);
    }
    pio_sm_config c = acsi_first_program_get_default_config(offset);
    sm_config_set_in_pins(&c, PIN_D0);              // base index for WAIT, IN
    sm_config_set_jmp_pin(&c, PIN_A1);              // for JMP
    sm_config_set_in_shift(&c, true, false, 32);    // Shift to right, autopush disabled
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_NONE);  // no FIFO join
    float div = (float)clock_get_hz(clk_sys) / 50000000;    // calc divider for 50 MHz, that's 20 ns per instruction
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    // pio_sm_set_enabled(pio, sm, true);
}

#endif

