// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// cmd_write //
// --------- //

#define cmd_write_wrap_target 0
#define cmd_write_wrap 5
#define cmd_write_pio_version 0

static const uint16_t cmd_write_program_instructions[] = {
            //     .wrap_target
    0xe000, //  0: set    pins, 0
    0x2029, //  1: wait   0 pin, 9
    0xe301, //  2: set    pins, 1                [3]
    0x4008, //  3: in     pins, 8
    0x8020, //  4: push   block
    0x20a9, //  5: wait   1 pin, 9
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program cmd_write_program = {
    .instructions = cmd_write_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = cmd_write_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config cmd_write_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + cmd_write_wrap_target, offset + cmd_write_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void cmd_write_program_init(PIO pio, uint sm, uint offset, uint pinWait, uint pinSet)
{
    pio_sm_config c = cmd_write_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pinWait);             // for WAIT, IN
    sm_config_set_out_pins(&c, pinSet, 1);          // for SET
    sm_config_set_in_shift(&c, true, false, 32);    // Shift to right, autopush disabled
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);  // Deeper FIFO as we're not doing any TX
    float div = (float)clock_get_hz(clk_sys) / 33250000;    // calc divider for 33.25 MHz, that's 30.08 ns per instruction
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

