// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// cmd_first //
// --------- //

#define cmd_first_wrap_target 0
#define cmd_first_wrap 4
#define cmd_first_pio_version 0

static const uint16_t cmd_first_program_instructions[] = {
            //     .wrap_target
    0x2029, //  0: wait   0 pin, 9
    0x00c0, //  1: jmp    pin, 0
    0x4008, //  2: in     pins, 8
    0x8020, //  3: push   block
    0x20a9, //  4: wait   1 pin, 9
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program cmd_first_program = {
    .instructions = cmd_first_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = cmd_first_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config cmd_first_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + cmd_first_wrap_target, offset + cmd_first_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void cmd_first_program_init(PIO pio, uint sm, uint offset, uint pinWait, uint pinJmp)
{
    pio_sm_config c = cmd_first_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pinWait);             // for WAIT, IN
    sm_config_set_jmp_pin(&c, pinJmp);              // for JMP
    sm_config_set_in_shift(&c, true, false, 32);    // Shift to right, autopush disabled
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);  // Deeper FIFO as we're not doing any TX
    float div = (float)clock_get_hz(clk_sys) / 33250000;    // calc divider for 33.25 MHz, that's 30.08 ns per instruction
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    // pio_sm_set_enabled(pio, sm, true);
}

#endif

