// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// cmd_read //
// -------- //

#define cmd_read_wrap_target 0
#define cmd_read_wrap 8
#define cmd_read_pio_version 0

static const uint16_t cmd_read_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x6008, //  1: out    pins, 8
    0xe000, //  2: set    pins, 0
    0x00c3, //  3: jmp    pin, 3
    0xe001, //  4: set    pins, 1
    0x00c7, //  5: jmp    pin, 7
    0x0005, //  6: jmp    5
    0xa442, //  7: nop                           [4]
    0x8020, //  8: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program cmd_read_program = {
    .instructions = cmd_read_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = cmd_read_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config cmd_read_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + cmd_read_wrap_target, offset + cmd_read_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static pio_sm_config cRead;
static PIO cmdReadPio;
static uint cmdReadSm;
static inline void cmd_read_program_init(PIO pio, uint sm, uint offset)
{
    cmdReadPio = pio;
    cmdReadSm = sm;
    #define PIO_READ_COUNT 13
    int pio_pins[PIO_READ_COUNT] = {PIN_D0, PIN_D1, PIN_D2, PIN_D3, PIN_D4, PIN_D5, PIN_D6, PIN_D7, PIN_CS, PIN_A1, PIN_INT, PIN_DRQ, PIN_ACK};
    int pio_dirs[PIO_READ_COUNT] = {     1,      1,      1,      1,      1,      1,      1,      1,      0,      0,       1,       1,       0};
    for (int i = 0; i < PIO_READ_COUNT; i++) {
        pio_gpio_init(pio, pio_pins[i]);
        pio_sm_set_consecutive_pindirs(pio, sm, pio_pins[0], 1, pio_dirs[i]);
    }
    cRead = cmd_read_program_get_default_config(offset);
    sm_config_set_out_pins(&cRead, PIN_D0, 8);          // for OUT
    sm_config_set_set_pins(&cRead, PIN_INT, 1);         // for SET
    sm_config_set_jmp_pin(&cRead, PIN_CS);              // for JMP
    sm_config_set_out_shift(&cRead, true, false, 32);   // Shift to right, autopush disabled
    sm_config_set_fifo_join(&cRead, PIO_FIFO_JOIN_NONE);  // no fifo joining
    float div = (float)clock_get_hz(clk_sys) / 50000000;    // calc divider for 50 MHz, that's 20 ns per instruction
    sm_config_set_clkdiv(&cRead, div);
    pio_sm_init(pio, sm, offset, &cRead);
    // pio_sm_set_enabled(pio, sm, true);
}
void configCmdReadForPIO(void)
{
    // DRQ is controlled by gpio, always driving H
    gpio_set_function(PIN_DRQ, GPIO_FUNC_SIO);
    gpio_put(PIN_DRQ, 1);
    // INT is controlled by PIO
    pio_gpio_init(cmdReadPio, PIN_INT);
    sm_config_set_set_pins(&cRead, PIN_INT, 1);        // for SET
    sm_config_set_jmp_pin(&cRead, PIN_CS);             // for JMP
}
void configCmdReadForDMA(void)
{
    // INT is controlled by gpio, always driving H
    gpio_set_function(PIN_INT, GPIO_FUNC_SIO);
    gpio_put(PIN_INT, 1);
    // DRQ is controlled by PIO
    pio_gpio_init(cmdWritePio, PIN_DRQ);
    sm_config_set_set_pins(&cRead, PIN_DRQ, 1);        // for SET
    sm_config_set_jmp_pin(&cRead, PIN_ACK);            // for JMP
}

#endif

