// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// scsi_read //
// --------- //

#define scsi_read_wrap_target 0
#define scsi_read_wrap 4
#define scsi_read_pio_version 0

static const uint16_t scsi_read_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 1
    0x7009, //  1: out    pins, 9         side 1
    0x2020, //  2: wait   0 pin, 0        side 0
    0xa842, //  3: nop                    side 0 [8]
    0x9020, //  4: push   block           side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program scsi_read_program = {
    .instructions = scsi_read_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = scsi_read_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config scsi_read_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + scsi_read_wrap_target, offset + scsi_read_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void scsi_read_program_init(PIO pio, uint sm, uint offset, uint inPin, uint sideSetPin)
{
    #define PIO_READ_COUNT 11
    int pio_pins[PIO_READ_COUNT] = {PIN_D0, PIN_D1, PIN_D2, PIN_D3, PIN_D4, PIN_D5, PIN_D6, PIN_D7, PIN_SEL_IO_DP_SDA, PIN_RST_CD_REQ_SCL, PIN_ACK};
    int pio_dirs[PIO_READ_COUNT] = {     1,      1,      1,      1,      1,      1,      1,      1,                 1,                  1,       0};
    for (int i = 0; i < PIO_READ_COUNT; i++) {
        pio_gpio_init(pio, pio_pins[i]);
        pio_sm_set_consecutive_pindirs(pio, sm, pio_pins[i], 1, pio_dirs[i]);
    }
    pio_sm_config cRead = scsi_read_program_get_default_config(offset);
    sm_config_set_out_pins(&cRead, PIN_D0, 9);          // for OUT
    sm_config_set_in_pins(&cRead, inPin);               // for WAIT, IN
    sm_config_set_sideset_pins(&cRead, sideSetPin);     // for SIDE_SET
    sm_config_set_out_shift(&cRead, true, false, 32);   // Shift to right, autopush disabled
    sm_config_set_fifo_join(&cRead, PIO_FIFO_JOIN_NONE);  // no fifo joining
    float div = (float)clock_get_hz(clk_sys) / 50000000;    // calc divider for 50 MHz, that's 20 ns per instruction
    sm_config_set_clkdiv(&cRead, div);
    pio_sm_init(pio, sm, offset, &cRead);
}

#endif

