// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// scsi_write //
// ---------- //

#define scsi_write_wrap_target 0
#define scsi_write_wrap 7
#define scsi_write_pio_version 0

static const uint16_t scsi_write_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 1
    0xb027, //  1: mov    x, osr          side 1
    0x200a, //  2: wait   0 gpio, 10      side 0
    0xa242, //  3: nop                    side 0 [2]
    0x4508, //  4: in     pins, 8         side 0 [5]
    0x308a, //  5: wait   1 gpio, 10      side 1
    0x9020, //  6: push   block           side 1
    0x1042, //  7: jmp    x--, 2          side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program scsi_write_program = {
    .instructions = scsi_write_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = scsi_write_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config scsi_write_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + scsi_write_wrap_target, offset + scsi_write_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
// to read N bytes, you must put N-1 into TX FIFO (one less)
static inline void scsi_write_program_init(PIO pio, uint sm, uint offset)
{
    #define PIO_WRITE_COUNT 10
    int pio_pins[PIO_WRITE_COUNT] = {PIN_D0, PIN_D1, PIN_D2, PIN_D3, PIN_D4, PIN_D5, PIN_D6, PIN_D7, PIN_RST_CD_REQ_CP, PIN_ACK};
    int pio_dirs[PIO_WRITE_COUNT] = {     0,      0,      0,      0,      0,      0,      0,      0,                  1,       0};
    for (int i = 0; i < PIO_WRITE_COUNT; i++) {
        pio_gpio_init(pio, pio_pins[i]);
        pio_sm_set_consecutive_pindirs(pio, sm, pio_pins[i], 1, pio_dirs[i]);
    }
    pio_sm_config cWrite = scsi_write_program_get_default_config(offset);
    sm_config_set_in_pins(&cWrite, PIN_D0);                     // for WAIT, IN
    sm_config_set_sideset_pins(&cWrite, PIN_RST_CD_REQ_CP);    // for SIDE_SET
    sm_config_set_in_shift(&cWrite, true, false, 32);   // Shift to right, autopush disabled
    sm_config_set_fifo_join(&cWrite, PIO_FIFO_JOIN_NONE);   // no fifo joining, we need both fifos
    float div = (float)clock_get_hz(clk_sys) / 50000000;    // calc divider for 50 MHz, that's 20 ns per instruction
    sm_config_set_clkdiv(&cWrite, div);
    pio_sm_init(pio, sm, offset, &cWrite);
}

#endif

