/* Resource Datei Indizes for FDD */

#define FDD              0   /* Formular/Dialog */
#define RADIO_SLOT1      2   /* BUTTON in Baum FDD */
#define RADIO_SLOT2      3   /* BUTTON in Baum FDD */
#define RADIO_SLOT3      4   /* BUTTON in Baum FDD */
#define IMAGENAME1       5   /* STRING in Baum FDD */
#define IMAGENAME2       6   /* STRING in Baum FDD */
#define IMAGENAME3       7   /* STRING in Baum FDD */
#define BTN_LOAD         8   /* BUTTON in Baum FDD */
#define BTN_CLEAR        9   /* BUTTON in Baum FDD */
#define BTN_NEW          10  /* BUTTON in Baum FDD */
#define BTN_SAVE         11  /* BUTTON in Baum FDD */
#define BTN_INTERNET     12  /* BUTTON in Baum FDD */
#define BTN_EXIT         13  /* BUTTON in Baum FDD */
