/* Resource Datei Indizes fÅr FDD */

#define FDD              0   /* Formular/Dialog */
#define RADIO_SLOT1      2   /* BUTTON in Baum FDD */
#define RADIO_SLOT2      3   /* BUTTON in Baum FDD */
#define RADIO_SLOT3      4   /* BUTTON in Baum FDD */
#define BTN_LOAD         5   /* BUTTON in Baum FDD */
#define BTN_CLEAR        6   /* BUTTON in Baum FDD */
#define BTN_NEW          7   /* BUTTON in Baum FDD */
#define BTN_SAVE         8   /* BUTTON in Baum FDD */
#define BTN_INTERNET     9   /* BUTTON in Baum FDD */
#define BTN_EXIT         10  /* BUTTON in Baum FDD */
#define STR_FILENAME     11  /* STRING in Baum FDD */
#define STR_PROGRESS     12  /* STRING in Baum FDD */
#define IMAGENAME1       13  /* STRING in Baum FDD */
#define IMAGENAME2       14  /* STRING in Baum FDD */
#define IMAGENAME3       15  /* STRING in Baum FDD */
