#ifndef VT52_H
#define VT52_H
/* from http://toshyp.atari.org/en/VT_52_terminal.html */
#define VT52_Bell() Cconout('\a')
#define VT52_Blink_off() Cursconf ( 3, 0 )
#define VT52_Blink_on() Cursconf ( 2, 0 )
#define VT52_Clear_down() Cconws("\33J")
#define VT52_Clear_eol() Cconws("\33K")
#define VT52_Clear_home() Cconws("\33E")
#define VT52_Clear_line() Cconws("\33l")
#define VT52_Clear_sol() Cconws("\33o")
#define VT52_Clear_up() Cconws("\33d")
#define VT52_Cur_down() Cconws("\33B")
#define VT52_Cur_home() Cconws("\33H")
#define VT52_Cur_left() Cconws("\33D")
#define VT52_Cur_off() Cursconf ( 0, 0 )
#define VT52_Cur_on() Cursconf ( 1, 0 )
#define VT52_Cur_right() Cconws("\33C")
#define VT52_Cur_up() Cconws("\33A")
#define VT52_Del_line() Cconws("\33M")
#define VT52_Get_blink() Cursconf ( 5, 0 )
#define VT52_Goto_pos(y,x) (Cconws("\33Y"),Cconout(' '+x),Cconout(' '+y))
#define VT52_Ink(c) (Cconws("\33b"),Cconout(c))
#define VT52_Ins_line() Cconws("\33L")
#define VT52_Line_feed() Cconout('\n')
#define VT52_Load_pos() Cconws("\33k")
#define VT52_Paper(c) (Cconws("\33c"),Cconout(c))
#define VT52_Return() Cconout('\r')
#define VT52_Rev_off() Cconws("\33q")
#define VT52_Rev_on() Cconws("\33p")
#define VT52_Save_pos() Cconws("\33j")
#define VT52_Scroll_up() Cconws("\33I")
#define VT52_Set_blink( rate ) Cursconf ( 4, rate )
#define VT52_Tab() Cconout('\t')
#define VT52_Wrap_off() Cconws("\33w")
#define VT52_Wrap_on() Cconws("\33v")

#endif