#ifndef VT52_H
#define VT52_H
/* from http://toshyp.atari.org/en/VT_52_terminal.html */
#define VT52_Bell()         Cconout('\a')
#define VT52_Blink_off()    Cursconf ( 3, 0 )
#define VT52_Blink_on()     Cursconf ( 2, 0 )
#define VT52_Clear_down()   (void) Cconws("\33J")
#define VT52_Clear_eol()    (void) Cconws("\33K")
#define VT52_Clear_home()   (void) Cconws("\33E")
#define VT52_Clear_line()   (void) Cconws("\33l")
#define VT52_Clear_sol()    (void) Cconws("\33o")
#define VT52_Clear_up()     (void) Cconws("\33d")
#define VT52_Cur_down()     (void) Cconws("\33B")
#define VT52_Cur_home()     (void) Cconws("\33H")
#define VT52_Cur_left()     (void) Cconws("\33D")
#define VT52_Cur_off()      Cursconf ( 0, 0 )
#define VT52_Cur_on()       Cursconf ( 1, 0 )
#define VT52_Cur_right()    (void) Cconws("\33C")
#define VT52_Cur_up()       (void) Cconws("\33A")
#define VT52_Del_line()     (void) Cconws("\33M")
#define VT52_Get_blink()    Cursconf ( 5, 0 )
#define VT52_Goto_pos(y,x)  ((void) Cconws("\33Y"),Cconout(' '+x),Cconout(' '+y))
#define VT52_Ink(c)         ((void) Cconws("\33b"),Cconout(c))
#define VT52_Ins_line()     (void) Cconws("\33L")
#define VT52_Line_feed()    Cconout('\n')
#define VT52_Load_pos()     (void) Cconws("\33k")
#define VT52_Paper(c)       ((void) Cconws("\33c"),Cconout(c))
#define VT52_Return()       Cconout('\r')
#define VT52_Rev_off()      (void) Cconws("\33q")
#define VT52_Rev_on()       (void) Cconws("\33p")
#define VT52_Save_pos()     (void) Cconws("\33j")
#define VT52_Scroll_up()    (void) Cconws("\33I")
#define VT52_Set_blink( rate ) Cursconf ( 4, rate )
#define VT52_Tab()          Cconout('\t')
#define VT52_Wrap_off()     (void) Cconws("\33w")
#define VT52_Wrap_on()      (void) Cconws("\33v")

#endif